# Étape 1 : Image Node pour développement
FROM node:22.18.0-alpine AS build

# Dossier de travail dans le conteneur
WORKDIR /app

# Copie des fichiers de dépendances
COPY package*.json ./

# Installation des dépendances Angular
RUN npm install -g @angular/cli && npm install

# Copie du reste du projet
COPY . .

# Expose le port Angular
EXPOSE 80

# Démarrage de l'app en mode développement
CMD ["ng", "serve", "--host", "0.0.0.0"]