export * from './persons/art-director.service';
export * from './persons/caster.service';
export * from './persons/costumier.service'
export * from './persons/decorator.service';
export * from './persons/director.service';
export * from './persons/editor.service';
export * from './persons/hair-dresser.service';
export * from './persons/makeup-artist.service';
export * from './persons/musician.service';
export * from './persons/photographer.service';
export * from './persons/producer.service';
export * from './persons/screenwriter.service';
export * from './persons/sound-editor.service';
export * from './persons/visual-effects-supervisor.service';
export * from './award.service';
export * from './country.service';
export * from './genre.service';
export * from './movie.service';

