export enum PersonType {
  ACTOR = 'ACTOR',
  PRODUCER = 'PRODUCER',
  DIRECTOR = 'DIRECTOR',
  SCREENWRITER = 'SCREENWRITER',
  DIALOGUE_WRITER = 'DIALOGUE_WRITER',
  MUSICIAN = 'MUSICIAN',
  PHOTOGRAPHER = 'PHOTOGRAPHER',
  COSTUMIER = 'COSTUMIER',
  DECORATOR = 'DECORATOR',
  EDITOR = 'EDITOR',
  CASTER = 'CASTER',
  ART_DIRECTOR = 'ART_DIRECTOR',
  SOUND_EDITOR = 'SOUND_EDITOR',
  VISUAL_EFFECTS_SUPERVISOR = 'VISUAL_EFFECTS_SUPERVISOR',
  MAKEUP_ARTIST = 'MAKEUP_ARTIST',
  HAIR_DRESSER = 'HAIR_DRESSER',
  STUNT_MAN = 'STUNT_MAN'
}